image: gradle:alpine

stages:
  - build
  
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: 
  - gradle build
  artifacts:
    paths:
      - build/distributions
      - build/libs/*.jar
    expire_in: 1 week
