image: gradle:alpine

stages:
  - build
  
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: 
  - mkdir bin
  - javac -d ./ src/javaTest/JavaTest.java
  - jar cvmf META-INF/MANIFEST.MF javaTest.jar  javaTest/JavaTest.class
  - ./gradlew build
  artifacts:
    paths:
      - javaTest.jar
